/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.JavaNBProject1;
import com.example.JavaNBProject1.Implementation.*;
import com.example.JavaNBProject1.Interfaces.Vehicle;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Vehicle car=new Car(25);
        car.start();
        System.out.println("Car speed:"+car.getSpeed());
       
        Vehicle electricCar=new ElectricCar(30);
        electricCar.start();
        System.out.println("Electric Car Fuel Efficiency....!"+((ElectricCar)electricCar).getFuelEfficiency());
        
        Vehicle motorcycle=new MotorCycle();
        motorcycle.start();
        System.out.println("MotorCycle speed:"+motorcycle.getSpeed());
    }
}
